# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\add_worker_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class AddWorkerUi(object):
    def setupUi(self, MainWindow,admin_id):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(501, 348)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(50, 50, 361, 231))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.admin_le = QtWidgets.QLineEdit(self.widget)
        self.admin_le.setObjectName("admin_le")
        self.admin_le.setText(admin_id)
        self.admin_le.setReadOnly(True)
        self.horizontalLayout_4.addWidget(self.admin_le)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.name_le = QtWidgets.QLineEdit(self.widget)
        self.name_le.setObjectName("name_le")
        self.horizontalLayout_3.addWidget(self.name_le)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.password_le = QtWidgets.QLineEdit(self.widget)
        self.password_le.setObjectName("password_le")
        self.horizontalLayout_2.addWidget(self.password_le)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.confirm_password_le = QtWidgets.QLineEdit(self.widget)
        self.confirm_password_le.setObjectName("confirm_password_le")
        self.horizontalLayout.addWidget(self.confirm_password_le)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_cancel = QtWidgets.QPushButton(self.widget)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_5.addWidget(self.btn_cancel)
        self.btn_accept = QtWidgets.QPushButton(self.widget)
        self.btn_accept.setObjectName("btn_accept")
        self.horizontalLayout_5.addWidget(self.btn_accept)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.password_le.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirm_password_le.setEchoMode(QtWidgets.QLineEdit.Password)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Admin"))
        self.label_2.setText(_translate("MainWindow", "Nombre"))
        self.label_3.setText(_translate("MainWindow", "Contraseña"))
        self.label_4.setText(_translate("MainWindow", "Confirmar contraseña"))
        self.btn_cancel.setText(_translate("MainWindow", "Cancelar"))
        self.btn_accept.setText(_translate("MainWindow", "Aceptar"))

        """START OWN CODE 
    ---------------------------------------------------------------------------------------------------------------------------------------------------
    """
    
    
    def showError(self,e):
            mensaje_error = QtWidgets.QMessageBox()
            mensaje_error.setIcon(QtWidgets.QMessageBox.Critical)
            mensaje_error.setWindowTitle('Error')
            mensaje_error.setText(str(e))
            mensaje_error.setStandardButtons(QtWidgets.QMessageBox.Ok)
            mensaje_error.exec_()
            
    def change_correct(self):
        warning_message = QtWidgets.QMessageBox()
        warning_message.setIcon(QtWidgets.QMessageBox.Warning)
        warning_message.setWindowTitle('Aviso')
        warning_message.setText("Se ha creado un nuevo becario correctamente")
        warning_message.setStandardButtons(QtWidgets.QMessageBox.Ok)
        warning_message.exec_()


