# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\admin_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 20, 160, 501))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.list_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.list_layout.setContentsMargins(0, 0, 0, 0)
        self.list_layout.setObjectName("list_layout")
        self.edit_list_btn = QtWidgets.QPushButton(self.centralwidget)
        self.edit_list_btn.setGeometry(QtCore.QRect(70, 540, 75, 23))
        self.edit_list_btn.setObjectName("edit_list_btn")
        self.change_password_btn = QtWidgets.QPushButton(self.centralwidget)
        self.change_password_btn.setGeometry(QtCore.QRect(150, 540, 121, 23))
        self.change_password_btn.setObjectName("change_password_btn")
        self.send_notification_btn = QtWidgets.QPushButton(self.centralwidget)
        self.send_notification_btn.setGeometry(QtCore.QRect(330, 550, 121, 23))
        self.send_notification_btn.setObjectName("send_notification_btn")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(510, 20, 160, 501))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.notifications_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.notifications_layout.setContentsMargins(0, 0, 0, 0)
        self.notifications_layout.setObjectName("notifications_layout")
        self.update_btn = QtWidgets.QPushButton(self.centralwidget)
        self.update_btn.setGeometry(QtCore.QRect(550, 550, 75, 23))
        self.update_btn.setObjectName("update_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.edit_list_btn.setText(_translate("MainWindow", "Editar lista"))
        self.change_password_btn.setText(_translate("MainWindow", "cambiar contraseña"))
        self.send_notification_btn.setText(_translate("MainWindow", "enviar notificacion"))
        self.update_btn.setText(_translate("MainWindow", "actualizar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
