# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\change_password_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ChangePasswordUi(object):
    def setupUi(self, ChangePasswordWindow):
        ChangePasswordWindow.setObjectName("ChangePasswordWindow")
        ChangePasswordWindow.resize(555, 300)
        self.centralwidget = QtWidgets.QWidget(ChangePasswordWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.old_password_imp = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.old_password_imp.sizePolicy().hasHeightForWidth())
        self.old_password_imp.setSizePolicy(sizePolicy)
        self.old_password_imp.setAutoFillBackground(False)
        self.old_password_imp.setStyleSheet("border: 4px solid #FFB6C1; border-radius: 10px; font-size: 20px; background-color: #FDF5E6; padding: 5px;")
        self.old_password_imp.setClearButtonEnabled(True)
        self.old_password_imp.setObjectName("old_password_imp")
        self.verticalLayout_5.addWidget(self.old_password_imp)
        self.new_password_imp = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_password_imp.sizePolicy().hasHeightForWidth())
        self.new_password_imp.setSizePolicy(sizePolicy)
        self.new_password_imp.setStyleSheet("border: 4px solid #FFB6C1; border-radius: 10px; font-size: 20px; background-color: #FDF5E6; padding: 5px;")
        self.new_password_imp.setObjectName("new_password_imp")
        self.verticalLayout_5.addWidget(self.new_password_imp)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cancel_btn = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_btn.setStyleSheet("background-color: #FFB6C1; color: white; border-radius: 10px; font-size: 20px; padding: 5px;")
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_2.addWidget(self.cancel_btn)
        self.accept_btn = QtWidgets.QPushButton(self.centralwidget)
        self.accept_btn.setStyleSheet("background-color: #FFB6C1; color: white; border-radius: 10px; font-size: 20px; padding: 5px;")
        self.accept_btn.setObjectName("accept_btn")
        self.horizontalLayout_2.addWidget(self.accept_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        ChangePasswordWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ChangePasswordWindow)
        QtCore.QMetaObject.connectSlotsByName(ChangePasswordWindow)

    def retranslateUi(self, ChangePasswordWindow):
        _translate = QtCore.QCoreApplication.translate
        ChangePasswordWindow.setWindowTitle(_translate("ChangePasswordWindow", "Cambiar Contraseña"))
        self.label_3.setStyleSheet(_translate("ChangePasswordWindow", "color: #FFB6C1; border-radius: 10px; background-color: #FDF5E6; padding: 10px;"))
        self.label_3.setText(_translate("ChangePasswordWindow", "Cambiar Contraseña"))
        self.old_password_imp.setPlaceholderText(_translate("ChangePasswordWindow", "Contraseña Antigua"))
        self.new_password_imp.setPlaceholderText(_translate("ChangePasswordWindow", "Contraseña Nueva"))
        self.cancel_btn.setText(_translate("ChangePasswordWindow", "Cancelar"))
        self.accept_btn.setText(_translate("ChangePasswordWindow", "Aceptar"))

    """START OWN CODE 
    ---------------------------------------------------------------------------------------------------------------------------------------------------
    """
    
    def showError(self, e):
            error_message = QtWidgets.QMessageBox()
            error_message.setIcon(QtWidgets.QMessageBox.Critical)
            error_message.setWindowTitle('Error')
            error_message.setText(str(e))
            error_message.setStandardButtons(QtWidgets.QMessageBox.Ok)
            error_message.exec_()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChangePasswordWindow = QtWidgets.QMainWindow()
    ui = Ui_ChangePasswordWindow()
    ui.setupUi(ChangePasswordWindow)
    ChangePasswordWindow.show()
    sys.exit(app.exec_())
