# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\edit_worker_list_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from model.worker import Worker


class EditWorkerListUi(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(501, 343)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cancel_btn = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_btn.setGeometry(QtCore.QRect(30, 290, 75, 23))
        self.cancel_btn.setObjectName("cancel_btn")
        self.accept_btn = QtWidgets.QPushButton(self.centralwidget)
        self.accept_btn.setGeometry(QtCore.QRect(350, 290, 75, 23))
        self.accept_btn.setObjectName("accept_btn")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 30, 471, 181))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.workers_cb = QtWidgets.QComboBox(self.widget)
        self.workers_cb.setObjectName("workers_cb")
        self.horizontalLayout.addWidget(self.workers_cb)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.username_le = QtWidgets.QLineEdit(self.widget)
        self.username_le.setObjectName("username_le")
        self.horizontalLayout_2.addWidget(self.username_le)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.change_password_btn = QtWidgets.QPushButton(self.widget)
        self.change_password_btn.setObjectName("change_password_btn")
        self.horizontalLayout_3.addWidget(self.change_password_btn)
        self.delete_user_btn = QtWidgets.QPushButton(self.widget)
        self.delete_user_btn.setObjectName("delete_user_btn")
        self.horizontalLayout_3.addWidget(self.delete_user_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        

    

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cancel_btn.setText(_translate("MainWindow", "Cancelar"))
        self.accept_btn.setText(_translate("MainWindow", "Aceptar"))
        self.label.setText(_translate("MainWindow", "Elige un Usuario para editar"))
        self.label_2.setText(_translate("MainWindow", "Usuario"))
        self.change_password_btn.setText(_translate("MainWindow", "Cambiar Contraseña"))
        self.delete_user_btn.setText(_translate("MainWindow", "Eliminar Usuario"))
    

        """START OWN CODE 
    ---------------------------------------------------------------------------------------------------------------------------------------------------
    """
    
    

        
    def show_workers(workers:list[Worker]):
        ...
    
    
    def showError(e:str):
        ...
    
    def get_selected_worker()->Worker:
        ...
        
