# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'principal_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class loginUI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1011, 574)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 50, 891, 480))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(120)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.UserName = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UserName.sizePolicy().hasHeightForWidth())
        self.UserName.setSizePolicy(sizePolicy)
        self.UserName.setAutoFillBackground(False)
        self.UserName.setStyleSheet("border: 4px solid #FFB6C1; border-radius: 10px; font-size: 20px; background-color: #FDF5E6;")
        self.UserName.setClearButtonEnabled(True)
        self.UserName.setObjectName("UserName")
        self.verticalLayout.addWidget(self.UserName)
        self.Password = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Password.sizePolicy().hasHeightForWidth())
        self.Password.setSizePolicy(sizePolicy)
        self.Password.setStyleSheet("border: 4px solid #FFB6C1; border-radius: 10px; font-size: 20px; background-color: #FDF5E6;")
        self.Password.setObjectName("Password")
        self.verticalLayout.addWidget(self.Password)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.boton1 = QtWidgets.QPushButton(self.layoutWidget)
        self.boton1.setStyleSheet("background-color: #FFB6C1; color: white; border-radius: 10px; font-size: 20px;")
        self.boton1.setObjectName("boton1")
        self.horizontalLayout_2.addWidget(self.boton1)
        self.BotonOk = QtWidgets.QPushButton(self.layoutWidget)
        self.BotonOk.setStyleSheet("background-color: #FFB6C1; color: white; border-radius: 10px; font-size: 20px;")
        self.BotonOk.setObjectName("BotonOk")
        self.horizontalLayout_2.addWidget(self.BotonOk)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.boton1.clicked.connect(self.button1_clicked)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SIFABUL LOGIN"))
        self.label_3.setStyleSheet(_translate("MainWindow", "color: #FFB6C1; border-radius: 30px;"))
        self.label_3.setText(_translate("MainWindow", "SIFABUL"))
        self.UserName.setPlaceholderText(_translate("MainWindow", "USERNAME"))
        self.Password.setPlaceholderText(_translate("MainWindow", "PASSWORD"))
        self.boton1.setText(_translate("MainWindow", "Borrar"))
        self.BotonOk.setText(_translate("MainWindow", "Aceptar"))
        self.label_4.setStyleSheet(_translate("MainWindow", "color: #FFB6C1; border-radius: 20px;"))
        self.label_4.setText(_translate("MainWindow", "SISTEMA DE FICHAJES UNIVERSIDAD DE LEÓN"))

        """START OWN CODE 
    ---------------------------------------------------------------------------------------------------------------------------------------------------
    """
    
    def button1_clicked(self):
        #delete the content
        self.UserName.clear()
        self.Password.clear()
    
    def showError(self,e):
            mensaje_error = QtWidgets.QMessageBox()
            mensaje_error.setIcon(QtWidgets.QMessageBox.Critical)
            mensaje_error.setWindowTitle('Error')
            mensaje_error.setText(str(e))
            mensaje_error.setStandardButtons(QtWidgets.QMessageBox.Ok)
            mensaje_error.exec_()
