# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\principal_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(730, 550)
        MainWindow.setMinimumSize(QtCore.QSize(730, 550))
        MainWindow.setMaximumSize(QtCore.QSize(730, 550))
        MainWindow.setBaseSize(QtCore.QSize(730, 550))
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 103, 83, 255), stop:0.930348 rgba(0, 157, 76, 255));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.288557 rgba(0, 157, 76, 255), stop:1 rgba(0, 103, 83, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 440, 611, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #FFB6C1; border-radius: 20px;\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(0, 0, 0, 0));")
        self.label_4.setObjectName("label_4")
        self.UserName = QtWidgets.QLineEdit(self.centralwidget)
        self.UserName.setGeometry(QtCore.QRect(200, 230, 451, 34))
        self.UserName.setStyleSheet("border: 4px solid #293133  ; border-radius: 10px; font-size: 20px; background-color:    #f2f5f0 ;")
        self.UserName.setText("")
        self.UserName.setClearButtonEnabled(True)
        self.UserName.setObjectName("UserName")
        self.Password = QtWidgets.QLineEdit(self.centralwidget)
        self.Password.setGeometry(QtCore.QRect(200, 290, 451, 34))
        self.Password.setStyleSheet("border: 4px solid\n"
" #293133; border-radius: 10px; font-size: 20px; background-color: #f2f5f0;")
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password.setObjectName("Password")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 230, 141, 34))
        self.label.setStyleSheet("border: 4px solid #145008  ; border-radius: 10px; font-size: 20px; background-color:    #3c852d  ;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 290, 141, 34))
        self.label_2.setStyleSheet("border: 4px solid #145008  ; border-radius: 10px; font-size: 20px; background-color:     #3c852d  ;")
        self.label_2.setObjectName("label_2")
        self.boton1 = QtWidgets.QPushButton(self.centralwidget)
        self.boton1.setGeometry(QtCore.QRect(360, 370, 263, 31))
        self.boton1.setStyleSheet("border: 4px solid #145008  ; border-radius: 10px; font-size: 20px; background-color:     #3c852d  ; color: white;\n"
"")
        self.boton1.setObjectName("boton1")
        self.BotonOk = QtWidgets.QPushButton(self.centralwidget)
        self.BotonOk.setGeometry(QtCore.QRect(110, 370, 241, 31))
        self.BotonOk.setStyleSheet("border: 4px solid #145008  ; border-radius: 10px; font-size: 20px; background-color:     #3c852d  ; color: white;")
        self.BotonOk.setObjectName("BotonOk")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 80, 181, 91))
        self.label_3.setObjectName("label_3")
        self.label_2.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.UserName.raise_()
        self.Password.raise_()
        self.boton1.raise_()
        self.BotonOk.raise_()
        self.label_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 730, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">SISTEMA DE FICHAJES UNIVERSIDAD DE LEÓN</span></p></body></html>"))
        self.UserName.setPlaceholderText(_translate("MainWindow", "USERNAME"))
        self.Password.setPlaceholderText(_translate("MainWindow", "PASSWORD"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; color:#ffffff;\">Usuario </span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; color:#ffffff;\">Contraseña</span></p><p><span style=\" color:#ffffff;\"><br/></span></p></body></html>"))
        self.boton1.setText(_translate("MainWindow", "Borrar"))
        self.BotonOk.setText(_translate("MainWindow", "Aceptar"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">(Ingresar logo aquí)</p></body></html>"))
